"""empty message

Revision ID: 100720fb6ef5
Revises: c660325b3012
Create Date: 2018-11-08 21:35:01.890238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100720fb6ef5'
down_revision = 'c660325b3012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Owners', sa.Column('pup_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'Owners', type_='foreignkey')
    op.create_foreign_key(None, 'Owners', 'puppies', ['pup_id'], ['id'])
    op.drop_column('Owners', 'puppy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Owners', sa.Column('puppy_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'Owners', type_='foreignkey')
    op.create_foreign_key(None, 'Owners', 'puppies', ['puppy_id'], ['id'])
    op.drop_column('Owners', 'pup_id')
    # ### end Alembic commands ###
