"""empty message

Revision ID: 939989106b88
Revises: 
Create Date: 2018-10-13 22:12:15.931209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939989106b88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
