"""empty message

Revision ID: 585cb2bf5bcc
Revises: 910742de1fcf
Create Date: 2018-11-25 14:51:02.292233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585cb2bf5bcc'
down_revision = '910742de1fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    # ### end Alembic commands ###
